[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://see.triggernode.com"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
major_version = 15

[studio]
enabled = true

[storage]
enabled = true

[analytics]
enabled = false

[functions]
enabled = true

[edge_runtime]
enabled = true

# Project configuration
project_id = "htykqrmczqockvmrsfui"

[[cron.jobs]]
name     = "scrapeDevexRate"
schedule = "0 3 * * *" # Every day at 03:00 UTC
command  = "supabase functions invoke scrapeDevexRate --no-verify-jwt" 