name: Deploy Supabase Edge Functions

on:
    push:
        branches: [main]
        paths:
            - 'supabase/functions/scrapeDevexRate/**'
            - '.github/workflows/edge-deploy.yml'

jobs:
    deploy-edge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Supabase CLI
              uses: supabase/setup-cli@v1
              with:
                  version: latest

            - name: Deploy Edge Function
              run: supabase functions deploy scrapeDevexRate --project-ref htykqrmczqockvmrsfui --use-api
              env:
                  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
                  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
